name: Build, Publish & Install

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'

jobs:
 build-publish-and-install-rc:
   runs-on: ubuntu-latest
   container:
     image: docker.io/dataloopai/py3.8.node16:1.74.14
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Install dependencies and build
       run: |
         npm i
         npm run build
     - name: Create valid app structure
       run: |
         mkdir -p ./panels/referenceViewer
         cp -r ./dist/. ./panels/referenceViewer
     - name: Publish & Install in project
       env:
         PROJECT_ID: "${{ secrets.PROJECT_ID_RC }}"
         BOT_EMAIL: "${{ secrets.BOT_EMAIL_RC }}"
         BOT_PASSWORD: "${{ secrets.BOT_PASSWORD_RC }}"
         ENV: "rc"
       run: |
         python3 create_app.py
